### ISSUE TITLE
Argument and function name consistency pass

### ISSUE THREAD

**Issue by alice-i-cecile** [DioxusLabs/sprawl#109]
We've made some changes to the argument and function names in #96, but are only touching non-public methods to ease the initial migration. I've made a conscious choice to prioritize clarity over both brevity and consistency with JavaScript, except in the case of `style.rs`.

The rest of the API should be cleaned up to match going forward.

To be more specific:

1. `node.rs` should match `forest.rs`: prefer the use of `child_index` over `index` and `parent` over `node` (where it makes sense).

**Comment by Weibye** [comment]
We have this method, and I'm trying to figure out if it makes sense to rename this `new_node()` -> `new_parent_node()` or `new_with_children()`?

```rust
    pub fn new_node(&mut self, style: Style, children: &[Node]) -> Result<Node, Error> {
        let node = self.allocate_node();
        let children =
            children.iter().map(|child| self.find_node(*child)).collect::<Result<ChildrenVec<_>, Error>>()?;
        let id = self.forest.new_node(style, children);
        self.add_node(node, id);
        Ok(node)
    }
```

**Comment by alice-i-cecile** [comment]
I would call this `new_with_children`
