### ISSUE TITLE
Consider renaming the crate

### ISSUE THREAD

**Issue by alice-i-cecile** [DioxusLabs/sprawl#11]
stretch2 is not exactly a compelling name.

The sooner we rebrand, the less confusing it will be.

**Comment by TimJentzsch** [comment]
There is also [another fork named stretch2](https://github.com/elbaro/stretch2) (but not maintained anymore), so I think renaming this one would be good going forward.

**Comment by alice-i-cecile** [comment]
Quick name ideas from me:

- `open_layout`: extremely functional but boring
- `stretchy`: a cute name that pays homage to the origins
- `perfect_fit`: evocative, moderately descriptive, memorable

Once we have a few decent suggestions, I think we should make a little poll on Github Discussions, and then go from there.

**Comment by drmason13** [comment]
To play on yoga as a theme: Pilates (/pɪˈlɑːtiːz/)

One downside is it's perhaps a little difficult to pronounce?

**Comment by CobaltCause** [comment]
How about `sprawl`? The job of a layouting engine is to *sprawl* all the elements onto the page/window/terminal/whatever, albeit in an organized fashion. I find the conflict of sprawl meaning "ungainly and awkward" and a layout engine's goal of being organized to be amusing.

**Comment by alice-i-cecile** [comment]
I think Pilates is a bit too strange for folks who aren't familiar with Yoga. And long-term at least, I'm not aiming to be a direct competitor: I want more than Flex!

I love `sprawl` though; that's really good.

I'm going to leave this up over the weekend, then we can do a poll with say 3-5 good options.

**Comment by ChristopherBiscardi** [comment]
maybe `playout`? play+layout.

**Comment by TimJentzsch** [comment]
> maybe `playout`? play+layout.

I like the concept, but this might collide with the [playout engine](https://github.com/ffplayout/ffplayout-engine) a bit.

**Comment by alice-i-cecile** [comment]
Yep; I definitely want to avoid name clashes with either existing UI (especially layout libraries), or Rust projects.

**Comment by ahenshaw** [comment]
> Quick name ideas from me:
>     * `stretchy`: a cute name that pays homage to the origins
'stretchy' is a great name.

**Comment by colepoirier** [comment]
As a play on 'layout' I like 'lei' (the name for hawaiian flower necklaces).

**Comment by alice-i-cecile** [comment]
A friend points out that `lei` could be a backronym for "Layout Engine Interface", which is quite clever.

**Comment by TimJentzsch** [comment]
`lei` seems to be taken already: https://crates.io/crates/lei

**Comment by alice-i-cecile** [comment]
Okay so feasible candidates so far:

- `stretchy`
- `perfect_fit`
- `sprawl`

`lei` and `playout` are sweet, but they have namespace collision issues.

`open_layout` is too bland, `pilates` is too obscure, `stretchmark` feels too negative.

I'll post and promote a poll on Saturday. @jkelleyrtp are you on board with those options?

**Comment by NickAcPT** [comment]
> I'll post and promote a poll on Saturday.

@alice-i-cecile Sorry to bother, where exactly will this poll be located? Is it something that the public (like me) can vote on?

**Comment by alice-i-cecile** [comment]
@NickAcPT https://github.com/DioxusLabs/stretch/discussions/42 poll!

**Comment by alice-i-cecile** [comment]
Alright, the results are in, and `sprawl` is the winner! Final release of `stretch2`, and then we'll do the rename.

![image](https://user-images.githubusercontent.com/3579909/169870893-8baa2fe2-72b4-47b0-bcc7-ee74adffe776.png)

**Comment by ahenshaw** [comment]
Ugh.  Stretchy, please! If naming conflict, then Stretchee.

**Comment by mnquintana** [comment]
I missed out on the original call for suggestions, but if you’re still open to suggestions, what about `taffy`?

I’m not a big fan of anything involving `lei` for cultural appropriation reasons (calling a library `yoga` was already bad enough).

**Comment by CobaltCause** [comment]
Keeping the theme of `sprawl`, what about `scatter`?

**Comment by ahenshaw** [comment]
+1 from me!
________________________________

**Comment by Weibye** [comment]
+1 for `taffy`, let's get this out-the-door asap so it does not happen again

**Comment by aatifsyed** [comment]
Sorry for taking `sprawl` - I was unaware of this project. Happy to hand it over to you - mine is only a small, not-publicised crate. I've invited @alice-i-cecile as an owner on crates.io, I'll happily take advice on next steps.

**Comment by Weibye** [comment]
> Sorry for taking `sprawl` - I was unaware of this project.

No worries! Apologies if our tone got a bit heated 😅 

@alice-i-cecile will contact you and we can figure this out 😄

**Comment by alice-i-cecile** [comment]
Follow-up:

> Honestly, thank you so much. That said, the team and I think that sprawl is a better fit for a web crawler than a layout library. I'm happy to let you have it; we have no shortage of good alternative names.

> I've declined the invitation and we'll pick a new name <3

Going to publish a stub crate today, and then submit a name-swap PR in preparation for a release.
