### ISSUE TITLE
Add #![warn(missing_docs)] crate-level rule

### ISSUE THREAD

**Issue by alice-i-cecile** [DioxusLabs/sprawl#22]
Docs matter, and this is a great way to verify that we've cleaned up the docs, and don't add new code without docs.

CI is required to pass for code to be merged, and warnings will block CI without being quite as annoying as deny or forbid for local development.

**Comment by CobaltCause** [comment]
There's also [`#[warn(clippy::missing_docs_in_private_items)]`](https://rust-lang.github.io/rust-clippy/v0.0.212/index.html#missing_docs_in_private_items). Requiring docs for internal items can make first-few-times contributions easier, although some may consider this lint too annoying to allow it to fail CI, which is understandable.

**Comment by alice-i-cecile** [comment]
Good call. I'm not opposed to doing so for this sort of crate. Let's see what it looks like; I'm not sure we're likely to have many private items in this style of crate.
