### ISSUE TITLE
Automate and host integrations for other languages

### ISSUE THREAD

**Issue by alice-i-cecile** [DioxusLabs/sprawl#25]
This was done by stretch originally, but relied on their own proprietary infrastructure.

We should either remove these bits of the code base, or navigate the JS / Kotlin / Swift / other ecosystems to do this properly again.

I have no personal need for these integrations: we should try to onboard maintainers who do care if we want to keep this functionality.

**Comment by alice-i-cecile** [comment]
There is a lot of assorted code and docs for this that I a) don't have a real interest in b) don't have the skills to maintain and c) don't have the time to maintain.

There's a lot of value in building out something solid for Rust-native tools first, and then adding bindings again later once we have critical mass + more stability.

@vaynnecol or @dprophete, are either of you interested?

**Comment by NickAcPT** [comment]
I'd love to see the Java/Kotlin bindings up-to-date.

**Comment by NickAcPT** [comment]
I'd love to see the Java/Kotlin bindings up-to-date.

Modern Java versions will have better support for FFI through [Project Panama](https://openjdk.java.net/projects/panama/) and it has a tool that can generate bindings based off of header files.

If there's a way to DllExport functions and somehow generate headers with the right structures and functions, it should be very easy to automate FFI for most languages ([SWIG](https://www.swig.org/) also comes to mind).


(Sorry for the double comment, submitted it by accident while typing)

**Comment by alice-i-cecile** [comment]
Sounds compelling. Are you interested in being a maintainer of those bindings? Like I said, I don't have the expertise myself :)

**Comment by NickAcPT** [comment]
> Sounds compelling. Are you interested in being a maintainer of those bindings? Like I said, I don't have the expertise myself :)

@alice-i-cecile As much as I'd love to, I don't have much experience when it comes to doing stuff with Rust, moreso having to deal with JNI from the Rust side.

Hence why I suggested going the route of exposing a public C api. After searching for a bit, I came across [this](https://michael-f-bryan.github.io/rust-ffi-guide/cbindgen.html) very interesting blog post that features the [cbindgen](https://github.com/eqrion/cbindgen) tool which would be the perfect candidate.

I mean, _name a good programming language that can't call exported C functions_. We could use cbindgen to our advantage to generate some initial c/c++ headers and then use any tools available to generate high quality bindings from those same headers. I'm sure that can be automated across different languages with some tools.

**Comment by alice-i-cecile** [comment]
Makes sense. Maybe we expose a language-agnostic public C API for now, and then let people add their own language-specific hooks as needed?

That lets us deprecate all of the cruft that we don't have the expertise for, but keeps the door open.

**Comment by simlay** [comment]
I'm late to the party here but figured I'd write some words about the current tools I've used for this sort of thing should someone come along and have interest.

I've used [flapigen-rl](https://github.com/Dushistov/flapigen-rs) for generating bindings to [Python](https://github.com/infinyon/fluvio-client-python) and [Java](https://github.com/infinyon/fluvio-client-java/). I'm relatively pleased with it. The harder parts of this were how to publish a package with pre-compiled rust.

I've recently been trying out [swift-bridge](https://github.com/chinedufn/swift-bridge) as it generates some higher level swift parts and have been relatively pleased. It's missing some pretty important features at the moment but one cool thing is that you can pre-compile the rust parts as a static library and bundle it into a swift package.

Mozilla maintains [uniffi-rs](https://github.com/mozilla/uniffi-rs) which I've not used but has some cool features.

**Comment by eviltik** [comment]
Really hard to find a serious layout engine in vanillia js. I've tested yoga-layout (with prebuild), and i'm here because of 
stretch-layout, both failed. I can't help because i don't know rust. Hope JS binding will reappear one day here !

**Comment by xavierzwirtz** [comment]
For what its worth, I have [ported the C bindings from stretch to taffy](https://github.com/xavierzwirtz/taffy-nix/). Pretty minor API changes overall.
