### ISSUE TITLE
Remove `.circleci` folder

### ISSUE THREAD

**Issue by TimJentzsch** [DioxusLabs/sprawl#38]
We don't use circle-ci, so we can probably just remove that folder.

**Comment by alice-i-cecile** [comment]
Definitely in agreement in the long-run. But as @mockersf pointed out, we're going to want to either use this for reference when reimplementing some more complex CI functionality (like publishing binding libraries), or remove that functionality completely (see #25).

**Comment by SaumyaBhushan** [comment]
@TimJentzsch I can do that if it needs to be removed. You can assign it to me.

**Comment by TimJentzsch** [comment]
Awesome! But let's keep it around for a bit longer to have it as reference, as @alice-i-cecile pointed out.
