### ISSUE TITLE
Define project toolchain in `rust-toolchain.toml`

### ISSUE THREAD

**Issue by TimJentzsch** [DioxusLabs/sprawl#56]
## What problem does this solve or what need does it fill?

Some people have `nightly` set as their default toolchain, but we use `stable` in CI.
This might cause inconsistencies with compile errors and clippy warnings that are generated locally vs. in the CI.

## What solution would you like?

Create a top-level `rust-toolchain.toml` file with the following content:
```toml
[toolchain]
channel = "stable"
```

## What alternative(s) have you considered?

Of course it's possible to set the toolchain using command overrides like `cargo +stable check` or `rustup override set stable`.

Personally I think it's better to define this directly in the source to avoid unintended behavior. I personally already encountered a clippy warning difference between CI and my local setup due to different toolchains.

## Additional context

Documentation on Rust toolchain overrides: <https://rust-lang.github.io/rustup/overrides.html>

**Comment by CobaltCause** [comment]
Another alternative might be to use Nix, which pins *everything*. I have an example Rust project that uses Nix in GitHub Actions [here](https://github.com/Cobaltcause/ghat), [this is the CI script](https://github.com/CobaltCause/ghat/blob/main/bin/ci), [this is the GHA Workflow](https://github.com/CobaltCause/ghat/blob/main/.github/workflows/ci.yml), and [here's an example run](https://github.com/CobaltCause/ghat/runs/6459167626?check_suite_focus=true#step:10:208). This setup also trivializes running CI locally (set up Nix/direnv/nix-direnv, then run `ci`). Downsides are that WSL is required on Windows and learning Nix/getting it to work might raise the barrier to entry.

**Comment by alice-i-cecile** [comment]
Nix might be a nice solution for CI, but won't solve the problem for contributors :)

**Comment by CobaltCause** [comment]
We can have `rust-toolchain.toml` and Nix at the same time, and Nix would work locally for those who have it set up without being a hard requirement for contributors. I totally understand if Nix is too much or otherwise undesirable though; I just thought I'd put it out there as an option.

**Comment by alice-i-cecile** [comment]
Yep, I'm on board with that plan :) I'll need guidance though; I haven't used Nix myself before.

**Comment by CobaltCause** [comment]
Okay I figured it out, [this diff](https://github.com/CobaltCause/ghat/commit/2f7bf0e72af4a00118212b34c4056c2b63eba394) makes Nix respect `rust-toolchain.toml`. I'd be happy to open a PR to add this stuff, including adding some docs/references for getting Nix working locally.

**Comment by alice-i-cecile** [comment]
Awesome, yes please @CobaltCause :)
